### ISSUE TITLE
fix: all collector images since 3.260917.0 crash at start-up: pyoaev 3.260904.0 pinned on a Python 3.14 image

### ISSUE THREAD

**Issue by SamuelHassine** [OpenAEV-Platform/collectors#603]
## Summary

Every collector image published since `3.260917.0` (`3.260917.0`, `3.260917.1`, `3.260921.0`) crashes at start-up. Nothing is fulfilled by any collector on the instances running them (Microsoft Defender, XTM One, Atomic Red Team, MITRE, NVD, ... all affected): every detection / prevention expectation is left to the Expectations Expiration Manager and fails 6 hours later.

Observed on the internal instance since the 2026-09-19 07:00 UTC scheduled runs (the last green run was 2026-09-18 09:00 UTC, before the upgrade group "first" moved to `3.260917.1`).

## Root cause

Two changes shipped together in `3.260917.0` and are incompatible with each other:

- collectors `1a10d6b` - feat(collectors): harmonize the collector project structure and workflow (#561) - moves every image from `python:3.13-alpine` to `python:3.14-alpine`, and pins `pyoaev = "3.260904.0"` in every `pyproject.toml`;
- client-python `128029a` - chore(pyoaev): compatibility support Python 3.14 (#337) - is the fix that makes pyoaev work on 3.14 (`RESTObject._create_managers` used `self.__annotations__`, which Python 3.14 no longer exposes on instances - PEP 649/749 deferred annotations), but it is only in pyoaev `3.260917.0`+.

The release script did not bump the pin (`3.260917.0` and `3.260921.0` still pin `pyoaev = "3.260904.0"`), so the images run a pyoaev without the fix on the interpreter that needs it. `main` has since been repointed to `pyoaev = "3.260921.0"` by #594 (`4a1c6aa`, merged AFTER the `3.260921.0` release commit), so `main` is fixed but no released image is.

## Evidence

Pod log (`kubectl -n customer-filigran-oaev logs atomic-red-team-...`):

```
  File "/collector/.venv/lib/python3.14/site-packages/pyoaev/daemons/collector_daemon.py", line 90, in _setup
    self.api.collector.create(config, collector_icon)
  ...
  File "/collector/.venv/lib/python3.14/site-packages/pyoaev/base.py", line 160, in _create_managers
    for attr, annotation in sorted(self.__annotations__.items()):
AttributeError: 'Collector' object has no attribute '__annotations__'. Did you mean: '__annotate_func__'?
```

Reproduced locally on CPython 3.14.5: `pyoaev==3.260904.0` fails to instantiate any REST object with that exact error, `pyoaev==3.260921.0` instantiates all 21 of them.

Why it looked healthy: `POST /api/collectors` succeeds server-side before the client blows up while building the response object, so every crash-loop restart refreshes `collector_last_execution` and the platform shows the collectors as alive.

Why no test caught it: `run_test.sh` force-installs pyoaev from git `main` after `poetry install`, so the test suites never run against the PyPI pin the image ships, and they mock the API anyway.

## Impact

- No expectation fulfilled by any collector on any instance running collectors `3.260917.0` to `3.260921.0`.
- All detection / prevention verdicts of that period are "Not detected" / "Not prevented" by expiration, not by the security platforms.
- Vulnerability injectors (e.g. Nuclei) are not affected: they are injectors, not collectors.

## Actions

1. Cut a hotfix release of the collectors from `main` (pin already at `3.260921.0`) - this is what actually restores the SaaS and on-prem instances on `3.260917.x` / `3.260921.0`.
2. Add a CI guard that boots the pinned pyoaev on the image's Python version so this drift can never ship again (PR to follow).
3. Check the injectors repository for the same Python bump / pin combination.

**Comment by SamuelHassine** [comment]
## Root-cause addendum: why the release override did not save the images

The image builds carry a `PYOAEV_GIT_REF_OVERRIDE` build argument meant to force-install client-python at the release tag (which would have carried the Python 3.14 fix: client-python tags `3.260917.0` and `3.260921.0` both contain #337). On every incident release it was a silent no-op:

- CircleCI passed `PYOAEV_GIT_BRANCH_OVERRIDE=$CIRCLE_BRANCH`, the wrong name for the Dockerfile's `ARG PYOAEV_GIT_REF_OVERRIDE`;
- and only on `main` builds, never on tag builds (`CIRCLE_BRANCH` is empty there).

The `3.260921.0` tag pipeline (CircleCI build 12395) logs `Build arguments:` empty and `Installing pyoaev (3.260904.0)`, i.e. the PyPI pin is what every published image runs.

#595 fixed the argument name and the tag handling, so from the next release the override applies; the PyPI pin remains what runs whenever the override is absent or fails, which is what the CI guard in #604 checks.

## Status

- Guard: #604 (green, waiting for a maintainer approval).
- Still required to restore the instances running `3.260917.x` / `3.260921.0`: a hotfix release of the collectors cut from `main` (pin already at `3.260921.0`).
- Still to check: the injectors repository for the same Python bump / pin combination.

**Comment by SamuelHassine** [comment]
## Why the pin stayed at 3.260904.0 on the incident releases (precise cause)

The collectors release is driven by `openaev_release.py` in OpenAEV-Platform/release, not by `scripts/release.py` of this repository. The orchestrator loads every `pyproject.toml` with `tomllib`, bumps the versions and dumps the file back with `tomli_w` (hence the section reshuffles in the `chore(release)` commits). Its pyoaev bump only understands the pre-#561 shapes: `[project].dependencies` entries (`pyoaev==x`) and the `[[tool.poetry.dependencies.pyoaev]]` array of tables (`version = "x"`). Since #561 the pin is a plain string (`pyoaev = "3.260904.0"`, `[project]` declares `dynamic = ["dependencies"]`), so the loop `for dep in deps["pyoaev"]: if "version" in dep` iterates the characters of the string and never matches: the bump is a silent no-op. Simulated against the current `atomic-red-team/pyproject.toml`: the pin is left untouched.

## Is a release from main safe now?

Yes, by two independent mechanisms, verified on `main`:

1. `main` already pins `pyoaev = "3.260921.0"` (#594), which contains the Python 3.14 fix (all 21 REST objects instantiate on CPython 3.14.5), and `openaev_release.py` blocks until `pyoaev==<new_version>` is published on PyPI before touching the collectors.
2. The tag image builds now pass `--build-arg PYOAEV_GIT_REF_OVERRIDE=${CIRCLE_TAG}` (#595) and both Dockerfiles force-install client-python at that tag into the runtime environment (alpine: the copied `.venv`, whose `bin` is first on `PATH`; ubi9: uninstall + reinstall into the system `python3.14`).

Remaining follow-up (not blocking): teach the orchestrator to bump the string pin, otherwise the `pyproject.toml` pin stays at `3.260921.0` on every future release and only the tag override keeps images on the released pyoaev. The injectors are not affected: still `python:3.13` images with the array-of-tables pin the orchestrator handles.
