### PR TITLE
ci(collectors): smoke-test the pinned pyoaev on the image Python version (#603)

### LINKED ISSUE #603: fix: all collector images since 3.260917.0 crash at start-up: pyoaev 3.260904.0 pinned on a Python 3.14 image
## Summary

Every collector image published since `3.260917.0` (`3.260917.0`, `3.260917.1`, `3.260921.0`) crashes at start-up. Nothing is fulfilled by any collector on the instances running them (Microsoft Defender, XTM One, Atomic Red Team, MITRE, NVD, ... all affected): every detection / prevention expectation is left to the Expectations Expiration Manager and fails 6 hours later.

Observed on the internal instance since the 2026-09-19 07:00 UTC scheduled runs (the last green run was 2026-09-18 09:00 UTC, before the upgrade group "first" moved to `3.260917.1`).

## Root cause

Two changes shipped together in `3.260917.0` and are incompatible with each other:

- collectors `1a10d6b` - feat(collectors): harmonize the collector project structure and workflow (#561) - moves every image from `python:3.13-alpine` to `python:3.14-alpine`, and pins `pyoaev = "3.260904.0"` in every `pyproject.toml`;
- client-python `128029a` - chore(pyoaev): compatibility support Python 3.14 (#337) - is the fix that makes pyoaev work on 3.14 (`RESTObject._create_managers` used `self.__annotations__`, which Python 3.14 no longer exposes on instances - PEP 649/749 deferred annotations), but it is only in pyoaev `3.260917.0`+.

The release script did not bump the pin (`3.260917.0` and `3.260921.0` still pin `pyoaev = "3.260904.0"`), so the images run a pyoaev without the fix on the interpreter that needs it. `main` has since been repointed to `pyoaev = "3.260921.0"` by #594 (`4a1c6aa`, merged AFTER the `3.260921.0` release commit), so `main` is fixed but no released image is.

## Evidence

Pod log (`kubectl -n customer-filigran-oaev logs atomic-red-team-...`):

```
  File "/collector/.venv/lib/python3.14/site-packages/pyoaev/daemons/collector_daemon.py", line 90, in _setup
    self.api.collector.create(config, collector_icon)
  ...
  File "/collector/.venv/lib/python3.14/site-packages/pyoaev/base.py", line 160, in _create_managers
    for attr, annotation in sorted(self.__annotations__.items()):
AttributeError: 'Collector' object has no attribute '__annotations__'. Did you mean: '__annotate_func__'?
```

Reproduced locally on CPython 3.14.5: `pyoaev==3.260904.0` fails to instantiate any REST object with that exact error, `pyoaev==3.260921.0` instantiates all 21 of them.

Why it looked healthy: `POST /api/collectors` succeeds server-side before the client blows up while building the response object, so every crash-loop restart refreshes `collector_last_execution` and the platform shows the collectors as alive.

Why no test caught it: `run_test.sh` force-installs pyoaev from git `main` after `poetry install`, so the test suites never run against the PyPI pin the image ships, and they mock the API anyway.

## Impact

- No expectation fulfilled by any collector on any instance running collectors `3.260917.0` to `3.260921.0`.
- All detection / prevention verdicts of that period are "Not detected" / "Not prevented" by expiration, not by the security platforms.
- Vulnerability injectors (e.g. Nuclei) are not affected: they are injectors, not collectors.

## Actions

1. Cut a hotfix release of the collectors from `main` (pin already at `3.260921.0`) - this is what actually restores the SaaS and on-prem instances on `3.260917.x` / `3.260921.0`.
2. Add a CI guard that boots the pinned pyoaev on the image's Python version so this drift can never ship again (PR to follow).
3. Check the injectors repository for the same Python bump / pin combination.

### PR DESCRIPTION
**Pull request by SamuelHassine**
### Proposed changes

Regression guard for #603: a CI job that boots the pyoaev release each collector PINS, on the Python version its images ship. It does not fix the running instances - a hotfix release from `main` (pin already at `3.260921.0`) does.

**Why.** Every collector image from `3.260917.0` to `3.260921.0` crashes at start-up: #561 moved the images to `python:3.14-alpine` while `pyproject.toml` kept `pyoaev = "3.260904.0"`, a release that predates the pyoaev Python 3.14 fix (client-python #337). `RESTObject._create_managers` reads `self.__annotations__`, which Python 3.14 no longer exposes on instances (PEP 649/749), so `CollectorDaemon._setup` dies on `api.collector.create(...)` - after the server-side `POST /api/collectors` succeeded, which is why `collector_last_execution` kept moving and the collectors looked healthy while no expectation was ever fulfilled.

**Why the release override did not save us.** The image builds carry a `PYOAEV_GIT_REF_OVERRIDE` build argument meant to force-install client-python at the release tag. On every one of those releases it was a silent no-op: CircleCI passed `PYOAEV_GIT_BRANCH_OVERRIDE=$CIRCLE_BRANCH` (wrong name for the Dockerfile's `ARG PYOAEV_GIT_REF_OVERRIDE`) and only on `main`, never on tag builds - the `3.260921.0` tag pipeline logs `Build arguments:` empty and `Installing pyoaev (3.260904.0)`. #595 fixed the argument name and the tag handling, so from the next release the override will apply; the PyPI pin is what runs whenever that override is absent or fails again, which is why this guard checks the pin.

**Why CI did not catch it.** `run_test.sh` force-installs pyoaev from git `main` right after `poetry install`, so the GitHub test suites never exercise the pin the image ships; the CircleCI test jobs do install the pin, but the suites mock the API and never instantiate a REST object.

**What.**

- `.github/scripts/smoke_pinned_runtime.py`: runs inside the collector's Poetry environment right after the Dockerfile's own install command (`poetry install --only main --no-root`, i.e. with the PINNED pyoaev). It instantiates every `RESTObject` under `pyoaev.apis` with a stub manager (the exact start-up path that crashed), then imports the collector the way its image starts it: every `[tool.poetry].packages` entry and the `[project.scripts]` entry module (`<package>.__main__`, what `python -m <package>` imports before calling `main()` - all 30 collectors guard the call). Exit 1 with one line per failure and a remedy per failure class (pyoaev pin vs collector code); `pkgutil` walk errors are recorded instead of aborting the walk or silently skipping a sub-package; the log shows the pin next to the installed version.
- `.github/scripts/build_test_matrix.py`: emits `runtime_matrix` / `has_shipped` with one entry per (collector, image Python version) for every collector that ships as an image (`pyproject.toml` plus `Dockerfile` or `Dockerfile_ubi9`), tests or not. The Python version is read from `FROM python:X.Y` (after `ARG` defaults, with `--platform` flags and registry prefixes) and from the `pythonX.Y` package the ubi9 images install, so both image flavours are covered and would each get their own job if they ever diverged. A collector whose Dockerfiles yield no version keeps an entry whose smoke job fails loudly. Unit-tested by `.github/scripts/test_build_test_matrix.py`, run by the `detect-test-files` job.
- `.github/workflows/tests-collectors.yml`: new `smoke-pinned-runtime` matrix job (`Pinned runtime <collector> py<X.Y>`), `fail-fast: false`, sets up the matrix Python, `pip install poetry==2.3.2`, `poetry install --only main --no-root`, runs the smoke script.

The guard stays a separate job rather than a step of `run_test.sh`: it must run on the image's interpreter with the image's install command, before any git override, and cover the 10 collectors that have no test suite.

### Testing Instructions

1. Local run on CPython 3.14.5 against `atomic-red-team` with the current pin: `python 3.14.5 / pyoaev 3.260921.0 (pinned 3.260921.0) / collector atomic-red-team` - `pyoaev REST objects instantiated: 21` - `collector packages and entry points imported: 2` - `OK`, exit 0. Same on `template` (src layout).
2. With `pyoaev==3.260904.0` installed instead, the guard fails with the production error on all 21 REST objects (`AttributeError("'Collector' object has no attribute '__annotations__'")`) and only the pin remedy, exit 1. A collector with a broken package / entry point fails with only the collector remedy, exit 1.
3. `python .github/scripts/build_test_matrix.py`: 20 collectors with tests, 30 pinned-runtime entries (all `py3.14`, alpine and ubi9 agree today). `python -m unittest discover -s .github/scripts -p "test_*.py"`: 7 tests OK.
4. CI on this PR: all 30 `Pinned runtime <collector> py3.14` jobs green, `Detect test files` runs the builder self-tests, CircleCI `ensure_formatting` / `linter` green.

### Related issues

* Closes #603

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

The 30 extra jobs cost about 25 s each and run under the workflow's existing `cancel-in-progress` concurrency group. A Dockerfile whose Python cannot be read (neither `FROM python:X.Y` nor an install of `pythonX.Y`) fails its own smoke job with a message pointing at the file and the parser, so the guard can never silently drop a collector from the matrix.

### CODE REVIEW

File: .github/scripts/smoke_pinned_runtime.py [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+        failures.append("no pyoaev REST object was found under pyoaev.apis")
+    if packages_checked == 0:
+        failures.append("no collector package is declared under [tool.poetry].packages")
+
+    for failure in failures:
+        print(f"FAIL {failure}")
+    if failures:
+        print(
+            "The pyoaev release pinned in pyproject.toml is not usable on the interpreter the"
+            " Dockerfile ships - bump the pin (or the base image) before releasing."
```
[the remark this answers is not in the document]
Comment (SamuelHassine) [reply .github/scripts/smoke_pinned_runtime.py]: Fixed in 8334622: pyoaev failures and collector failures are now two separate lists, each with its own remedy line. The "bump the pin (or the base image)" hint only prints when a REST object failed to instantiate (or pyoaev.apis failed to import), and a collector-side hint ("fix the collector or its dependency constraints") prints when one of the collector's own start-up imports failed. The collector check also grew while I was there: on top of the [tool.poetry].packages it now imports the [project.scripts] entry module (<package>.__main__, what python -m <package> runs before calling main()), so a src-layout collector is exercised beyond src/__init__.py. The three cases (pin failure only, collector failure only, both) were exercised locally on CPython 3.14.5.

**Review by SamuelHassine — COMMENTED** [review]
Review verdict: APPROVE. Posted as a review comment because GitHub refuses a self-approval (this review ran under the PR author's account); a second maintainer's approval is still needed for the required review.

Approving after a full review pass (all changed files read in full, plus their callers: the collector Dockerfiles of both flavours, run_test.sh, the CircleCI config at the incident tags and on main, pyoaev's RESTObject/_create_managers, and every collector's __main__ entry point).

- The guard does what it claims: with pyoaev 3.260904.0 on CPython 3.14 it fails on all 21 REST objects with the exact production AttributeError, with 3.260921.0 it passes; the collector start-up imports are exercised the way python -m <package> does it, with main() never called (all 30 entry points guard it).
- Both image flavours are covered (Dockerfile and Dockerfile_ubi9, one matrix entry per Python version), the version parser is unit-tested in the detect job, and a collector whose Python cannot be read fails its own job loudly instead of vanishing from the matrix.
- Failures are reported per class (pyoaev pin vs collector code) with a remedy each, and pkgutil walk errors can no longer abort the walk or silently drop a sub-package.
- CI is green on the head commit: GitHub Actions (detect + self-tests, 20 test jobs, 30 pinned-runtime jobs, signed commits, linked issue, title), CircleCI (ensure_formatting, linter, 30 test jobs, image builds). Both Copilot threads are addressed and resolved.

This PR is the regression guard only: the running 3.260917.x / 3.260921.0 instances are restored by a hotfix release cut from main.

**Comment by SamuelHassine** [comment]
Review and fix pass summary (PR #604, closes #603).

**What was red and why**

- First head `78419eb`: CircleCI `ensure_formatting` failed on a comprehension Black wanted wrapped in `smoke_pinned_runtime.py` (fixed by the amended `b4324e8`), and `test-elastic` failed on a PyPI read timeout (green on every run since). GitHub did not synchronize the PR to the force-pushed `b4324e8` for about 45 minutes (no `head_ref_force_pushed` event, no GitHub Actions run on it), so `gh pr checks` kept showing the old red rollup; the next push (`8334622`) re-synchronized everything.
- On `8334622`, CircleCI `test-microsoft-defender` failed while `poetry install --with test` downloaded `msgraph-sdk` (`ConnectionResetError(104)` from PyPI) - an infrastructure flake in a job this PR does not touch; re-run via the empty commit `acbec89`, green.

**Review changes pushed (`8334622`)**

- `build_test_matrix.py` now resolves the Python version of both image flavours (`FROM python:X.Y` in `Dockerfile`, the `pythonX.Y` package installed by `Dockerfile_ubi9`) and emits one runtime-matrix entry per (collector, version); the fragile `sed` on the FROM line is gone, the parser handles `--platform` flags, registry prefixes, `ARG` defaults and lowercase `FROM`, and is unit-tested (`test_build_test_matrix.py`, run by the `detect-test-files` job). A collector with no readable version keeps an entry whose job fails with a message pointing at the file and the parser.
- `smoke_pinned_runtime.py` also imports the `[project.scripts]` entry module (`<package>.__main__`, what `python -m <package>` runs before `main()` - verified that all 30 guard the call and have no env-dependent import-time code), records `pkgutil` walk errors instead of aborting or silently skipping a sub-package, prints the pin next to the installed version, and reports pyoaev failures and collector failures as two classes with their own remedy (the Copilot finding).
- The workflow comment and the PR description now state the real release mechanics, established from the CircleCI logs of the `3.260921.0` tag pipeline (build 12395 prints `Build arguments:` empty and `Installing pyoaev (3.260904.0)`): the `PYOAEV_GIT_REF_OVERRIDE` build argument was a silent no-op on every incident release (wrong name `PYOAEV_GIT_BRANCH_OVERRIDE`, and only set on `main`, never on tag builds). #595 fixed both, so the override will apply from the next release; the pin is what runs whenever it is absent or fails again, which is what this job guards.

**Review threads**

- `#discussion_r4073503440` (Black line length): fixed in `b4324e8`, resolved.
- `#discussion_r4073503497` (failure summary conflates pyoaev and collector failures): fixed in `8334622`, replied, resolved.
- Copilot overview items without a thread (ubi9 variants omitted, uncaught package-walk errors, override coverage) are all addressed above.

**Still open for the maintainers**

- The collectors hotfix release from `main` (pin already at `3.260921.0`) is what restores the instances running `3.260917.x` / `3.260921.0`; this PR does not.
- #603 action 3 (check the injectors repository for the same Python bump / pin combination) is not covered here.
- The required approving review must come from another maintainer: GitHub refused the approval from the PR author's account, so the review verdict above is recorded as a comment.
